name: CI/CD - Build & Deploy (App Service Container)

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/api.yml"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # 允许推送到 GHCR

    env:
      IMAGE_NAME: ghcr.io/hanshuoxue/alex-api:${{ github.sha }}
      WEBAPP_NAME: api-alex-12345 # ← 改成你的 App Service 名称

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: ./api # ← Dockerfile 所在目录
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 更新 App Service 的容器镜像为刚才推到 GHCR 的版本
      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_NAME }}
