name: CI/CD - Build & Deploy (App Service Container)

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/api.yml"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read # read-only access to the repository
      packages: write # allow pushing to GHCR

    env:
      IMAGE_NAME: ghcr.io/hanshuoxue/alex-api:${{ github.sha }} # 40 char sha to tag the image
      WEBAPP_NAME: api-alex-12345 # ← change to your App Service name

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # ghcr.io/username
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: ./api # ← Dockerfile directory
          platforms: linux/amd64 # must be linux/amd64 instead of apple silicon
          push: true # push the image to GHCR after building
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Update App Service container image to the version pushed to GHCR
      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_NAME }}
